version: "3.9"

services:
  infotree-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infotree-client
    ports:
      - "3001:80"  # Map container port 80 to host 3001
    restart: unless-stopped
